// Autogenerated from Pigeon (v10.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class Stock {
  Stock({
    this.title,
  });

  String? title;

  Object encode() {
    return <Object?>[
      title,
    ];
  }

  static Stock decode(Object result) {
    result as List<Object?>;
    return Stock(
      title: result[0] as String?,
    );
  }
}

class _FlutterStocksApiCodec extends StandardMessageCodec {
  const _FlutterStocksApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Stock) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return Stock.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterStocksApi {
  static const MessageCodec<Object?> codec = _FlutterStocksApiCodec();

  void showStocks(List<Stock?> stocks);

  static void setup(FlutterStocksApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.FlutterStocksApi.showStocks', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.FlutterStocksApi.showStocks was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<Stock?>? arg_stocks = (args[0] as List<Object?>?)?.cast<Stock?>();
          assert(arg_stocks != null,
              'Argument for dev.flutter.pigeon.FlutterStocksApi.showStocks was null, expected non-null List<Stock?>.');
          api.showStocks(arg_stocks!);
          return;
        });
      }
    }
  }
}

class _HostStocksApiCodec extends StandardMessageCodec {
  const _HostStocksApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is Stock) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return Stock.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class HostStocksApi {
  /// Constructor for [HostStocksApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HostStocksApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _HostStocksApiCodec();

  Future<void> loadStocks(Stock arg_stock) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.HostStocksApi.loadStocks', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_stock]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}
